### ISSUE TITLE
Multiple Wattpilot‘s

### ISSUE THREAD

**Issue by thecem** [joscha82/wattpilot#21]
How is it possible to integrate more than one Wattpilot?
1. Configure it via docker environment.
2. One container per Wattpilot.

In both cases MQTT must be able to distinguish the WP via Topic, after testing this is not the case (multiple container).

Thank’s a lot!

**Comment by ahochsteger** [comment]
@thecem, yes this should be possible with two separate docker containers.
You will have to take care, that both get a unique topic prefix and a unique MQTT client ID which you can control using these environment variables:
* `MQTT_TOPIC_BASE` (uses `wattpilot` by default)
* `MQTT_CLIENT_ID` (uses `wattpilot2mqtt` by default)
Hope that helps!
Let me know if it worked :-)

**Comment by thecem** [comment]
With the following stack config it works:

THX!

```
version: '3'
services:
  wattpilot_**%ID%**:
    image: ghcr.io/joscha82/wattpilot:main
    command: server
    restart: always
    network_mode: host
    environment:
      - HA_ENABLED=true
      - MQTT_ENABLED=true
      - MQTT_HOST=homeassistant
      - MQTT_USERNAME=mqttuser
      - MQTT_PASSWORD=mqttpass
      - MQTT_CLIENT_ID=wattpilot2mqtt_**%ID&**
      - MQTT_TOPIC_BASE=wattpilot_**%ID%**
      - MQTT_PUBLISH_MESSAGES=true
      - WATTPILOT_HOST=**%IP from ID%**
      - WATTPILOT_PASSWORD=sec
```
